### ISSUE TITLE
geoclue not found

### ISSUE THREAD

**Issue by domguard** [inzanity/geoclue-mock#2]
Under Debian 6.0.12-1 / Bookworm testing
When I launch configure, I get : 

`configure: error: Package requirements (geoclue) were not met:

Package 'geoclue', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GEOCLUE_CFLAGS
and GEOCLUE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
`

Installing dev, libraries, putting all pkg-config paths I could find does not change anything
What the GEOCLUE_CFLAGS and GEOCLUE_LIBS variables could be to achieve install ?

thank you!

**Comment by inzanity** [comment]
Unfortunately this project is mostly obsolete, since GeoClue has moved to version 2.0, a nearly complete rewrite. I have no plans to make a port, but PRs welcome.
